### PR TITLE
convert_image接口修改

### PR DESCRIPTION
**Pull request by zt-pro**
convert_image接口修改

### CODE REVIEW

**Comment by zt-pro** [comment]
Please release a new version of the composer package






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EcomPHP/shopee-php"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EcomPHP/shopee-php] convert_image接口修改 (PR #4)





 
Closed #4.

**Comment by zt-pro** [comment]
Please release a new version of the composer package

**Comment by nVuln** [comment]
your PR is rejected for some reason
1. you don't provide any detail about your PR or any error related
2. I just looked into your code and it's not matched with Shopee document here: https://open.shopee.com/documents/v2/v2.returns.convert_image?module=102&type=1

**Comment by zt-pro** [comment]
> your PR is rejected for some reason
> 
> 1. you don't provide any detail about your PR or any error related
> 2. I just looked into your code and it's not matched with Shopee document here: https://open.shopee.com/documents/v2/v2.returns.convert_image?module=102&type=1

base on your code,Shopee return error with reason "return_sn is a required parameter"
411727231679_ pic
and i ask them by ticket,they response me,the return_sn is must in the url,but your code is not do this,so i change it

**Comment by nVuln** [comment]
based on your report, I moved `return_sn` to query params instead of post params
already tagged it `v1.1.1`

**Pull request closed without merging**
